// src/app/layout.tsx
import type { Metadata } from 'next';
import { Gochi_Hand, Open_Sans, Poppins } from 'next/font/google';
import './globals.css';
import PageLoader from './components/PageLoader'; // 👈 IMPORTE O NOVO COMPONENTE

const gochiHand = Gochi_Hand({
  variable: '--font-gochi-hand',
  subsets: ['latin'],
  weight: '400',
});

const openSans = Open_Sans({
  variable: '--font-open-sans',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

const poppins = Poppins({
  variable: '--font-poppins',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" className='scroll-smooth'>
      <body
        className={`
          ${gochiHand.variable}
          ${openSans.variable}
          ${poppins.variable}
          antialiased bg-b noise-[128,50,5]
          select-none
        `}
      >
        <PageLoader>{children}</PageLoader>
      </body>
    </html>
  );
}